enum ACTION {
  SET_HEADER_BUTTON_TITLE = "SET_HEADER_BUTTON_TITLE",
  SET_WEEK = "SET_WEEK",
  SET_LANG = "SET_LANG",

  GET_ADRESSES = "GET_ADRESSES",
  SET_ADDRESSES = "SET_ADDRESSES",
  SET_ADDRESS = "SET_ADDRESS",
  FILTER_ADDRESSES = "FILTER_ADDRESSES",

  GET_FACULTIES = "GET_FACULTIES",
  SET_FACULTIES = "SET_FACULTIES",
  SET_FACULTY = "SET_FACULTY",
  FILTER_FACULTIES = "FILTER_FACULTIES",

  GET_CABINETS = "GET_CABINETS",
  SET_CABINETS = "SET_CABINETS",
  SELECT_CABINET = "SELECT_CABINET",
  DESELECT_CABINET = "DESELECT_CABINET",
  FILTER_CABINETS = "FILTER_CABINETS",
  CLEAN_CABINETS = "CLEAN_CABINETS",

  SELECT_EDUCATOR = "SET_EDUCATOR",
  DESELECT_EDUCATOR = "DESELECT_EDUCATOR",
  SET_EDUCATORS = "SET_EDUCATORS",
  UPD_FILTER_VALUE = "UPD_FILTER_VALUE",
  FILTER_EDUCATORS = "FILTER_EDUCATORS",

  GET_CABINET_TIMETABLE = "GET_CABINET_TIMETABLE",
  SET_CABINET_TIMETABLE = "SET_CABINET_TIMETABLE",
}

export default ACTION;
